project_id = "zrubgpirebvulnniyjql"

[functions.binance-yields]
verify_jwt = false

[functions.bsc-yields]
verify_jwt = false

[functions.aster-onchain]
verify_jwt = false

[functions.lp-locking]
verify_jwt = false
